---
title: "Final Project Proposal"
subtitle: "COMM 7370 | Spring 2026"
format:
  pdf:
    geometry: 
      - top=.75in
      - left=.8in
      - right=.8in
    urlcolor: blue
    number-sections: true
  html:
    code-fold: true
    toc: true
    theme: sandstone
---

# Overview

What you have learned throughout the course of the semester will culminate in final project that consists of a research proposal (or paper, if you have data) and an in-class presentation. You will explicate a research problem, conduct a literature review, formulate hypotheses, devise the methodology and analytic strategy, and outline your data analysis (or conduct your data analysis).

Your project proposal or paper should include:

-   An outline of the research problem and its relevance for a specific discipline and society.

-   A literature review to support your theoretical framework and translates the problem into research questions and testable hypotheses.

-   A discussion of the measures used in your project and justification for measures and analytic procedures, or the analysis, results, and discussion sections of the paper.

You will present a project prospectus in class. Your prospectus should include all the components of your final project and a plan for accomplishing each component. In addition to presenting your proposal or paper, you will serve as a reviewer for your peers.

## Requirements {#sec-req}

All proposals should follow APA style guidelines. Your proposal should contain:(1) a cover page, (2) a single-page project summary, (3) an introduction to the problem and its importance and contribution to the discipline and society, (4) a thorough review of literature relevant to your concepts of interest, (5) hypotheses and/or research questions, (6) methodology detailing measures and analytic approach, (7) a link to your preregistration, (8) appropriate tables and figures, and (9) references.

Your final proposal should not exceed 8,000 words (not inclusive of cover page, project summary, tables, figures, or references).

# Elements of the Final Project

## Project Prospectus

This is a 1,500 - 2,000 word document that outlines your project topic, the research problem, and its disciplinary and societal relevance and importance. The prospectus should also clearly identify (with citations and references) concepts of interest and their conceptual definitions. In addition to the 1,500 - 2,000 words, there should be an outline of your proposal included in the prospectus.

Submit this as a PDF document on Canvas.

You will also present this in class in Week 6. Each student will have 20 minutes to present their work followed by 10 minutes of Q\&A and discussion. The goal of the presentation is to learn to constructively offer critiques to your peers and receive feedback on your own project.

## Penultimate Paper

This is the penultimate version of your project paper. If you were submitting to paper to a funding agency, you should be comfortable submitting this version of it. The requirements of the final paper apply (see @sec-req).

Submit this as a PDF document on Canvas.

## Final Project Proposal or Paper and Response

I will offer feedback on the penultimate version of your proposal. You can choose whether to incorporate the feedback offered. However, you will prepare a response to my comments that accompany the final version of your proposal.

This is similar to responding to reviewer comments during the publication process. We will review the format of a response to reviewers in class. In addition to a response, you will revise and resubmit your proposal, indicating where revisions have been made.

You will submit this as a single PDF document on Canvas in addition to the final proposal.

You will also review at least one other students' proposal or paper. More information will be given during the course.

## Project Presentation

You will present your proposal during class at the end of the semester (see syllabus for specific date). Each student will have 20 minutes to present their work followed by 10 minutes of Q\&A and discussion.

Prior to the presentations, I will share the projects with the class. Please come prepared to ask questions and discuss your peers' proposals.

You will serve as a respondent for the proposal/paper that you reviewed.

# Miscellanea

I am always open to helping you with your project or any other aspect of this course. Please email me early if you get stuck or need help. That said, I cannot review full drafts of paper before the deadline. However, I am willing to discuss your outline (included in the prospectus).

Remember that the more work you put in, the better feedback you will receive. There are writing/data analysis workshops built into our schedule at the end of the semester. This is protected time for you to write. In order to make these productive, please come prepared. This will look different for each student but, in general, the more work you can accomplish early, the better. 

