---
title:  |
        | COMM 7370
        | Quantitative Communication Research
subtitle: |
          |
          | Spring 2023
          |
          | Wed 2 - 4:50 pm
          | LNCO 2630
author: |
        | Sara K. Yeo
        | [sara.yeo@utah.edu](sara.yeo@utah.edu)
format: 
  pdf:
    documentclass: scrartcl
    sansfont: Times New Roman
editor: visual
---

This graduate seminar is an introductory course in quantitative research for communication-related topics. We will examine how research questions are developed into a research project. Additionally, we will learn how to select appropriate research techniques, measure concepts, draw samples, interpret results, and communicate our research.

Key topics include:

-   Formalizing hypotheses and research questions grounded in theory
-   Testing hypotheses and research questions
-   Conceptual and operational definitions
-   Measurement, sampling, and research design
-   Data analysis in communication research

The main objectives of this course are:

1.  To offer a theoretical perspective on quantitative social science research with a focus on surveys and experiments in communication.
2.  To familiarize you with data analysis using two software packages, R and IBM SPSS Statistics.
3.  To stimulate ideas for original research and help you conduct data analysis for your own future research projects.
4.  To generate a class study and paper using quantitative research for presentation at a conference and publication in a journal.

It is challenging to grasp research methods without doing research. As a result, much of the course will be spent linking concepts to survey questions, collecting and analyzing data, trying to make sense of output, and linking data analysis to research questions and hypotheses. We will also have working labs at the end of the semester during which we will work on our class manuscript.

# Required Readings

For most weeks, I have compiled a non-exhaustive set of readings. I will post the weekly reading list on Canvas. If PDFs are not available through the Marriott Library resources, the files will be posted on Canvas.

You are expected to complete these readings before the start of each meeting. These readings are intended as a point-of-entry into the week\\'s content. They may also be useful if you are trying to compile a reading list for your preliminary examinations.

# Computer Software

You will need Microsoft Office (Word, Excel, PowerPoint) and software for data analysis ([R](https://www.r-project.org/), [IBM SPSS Statistics](https://onthehub.com/products/a4db50af-41be-eb11-813b-000d3af41938)). You will have to either purchase IBM SPSS Statistics or use it through the remote software tools via the [Marriott Library](https://lib.utah.edu/services/knowledge-commons/remote-software/). Please note that you do not have to have them ready for the first day of class. We will set these up during class when needed.

Additionally, access to a text-editor (e.g., Wordpad, TextEdit, Notepad++) and Adobe Acrobat (free for UofU students) is recommended.

You will need access to [Canvas](https://utah.instructure.com/). I expect you to check the course website on Canvas regularly. Announcements, assignments, readings, discussions, etc., will be posted there. You should be familiar with and comfortable using Canvas and Zoom. If you need help with Canvas, visit the [Canvas Getting Started Guide for Students](https://community.canvaslms.com/docs/DOC-10701).

# Course Requirements

Your grade in this course will be based on the following:

-   Weekly response papers (30%)
-   Discussion leadership (30%)
-   Lab assignments (20%)
-   Participation and contribution to class paper (20%)

## Weekly Response Papers

asdasd

## Discussion Leadership

sdadas

## Assignments

-   Concept explication assignment
-   

## Participation and Contribution to Class Paper

asdasd

# Course Policies

**Course civility.** By enrolling in this course, you agree to (i) respect all members of the course; (ii) pay attention and participate in all classes and activities; and (iii) avoid unnecessary disruption during class meetings (e.g., text messaging, checking social media, doing work for other classes). This list represents the minimal standards to make the classroom a productive learning space for all. Your final grade may be affected each time you engage in disruptive and/or disrespectful behaviors.

Communication allows us to engage with others and broaden our perspectives. How we discuss concepts, in the physical or virtual classroom, is part of that process. Our diverse perspectives and experiences will inform and enhance those discussions. Each member of the class is expected to foster a respectful, generous, and supportive online environment that makes room for productive difference and reasoned debate. Spirited discussion is encouraged. However, incivility is a different story entirely. Here is the basic netiquette that will be expected in the course:

-   Always address your classmates by name. There is a human being on the other side of the room who also has struggles, doubts, and bad days.
-   Disagreement is encouraged. Approach differences in a manner that seeks clarity and better understanding by asking productive questions and by providing counterarguments that are supported with evidence.
-   Anytime you have a strong emotional reaction to something, pause before responding. Always seek to provide an argument that is supported by **credible evidence** based on the theories we discuss in this course.

**E-mail policy. Use your University email account to contact me; I typically will not respond to emails originating from a non-University account (e.g., Google, Yahoo, etc.)**. Using a non-University account runs the risk of your message being diverted to Spam and your message may not reach me in a timely fashion, if at all.

Emails should be written clearly and professionally, using appropriate salutations (e.g., Dr. or Prof. Yeo) with correct spelling and grammar. **Emails that do not conform to these rules will not receive a response.**

If you need to contact me, please send a message from your University of Utah email account to [sara.yeo\@utah.edu](mailto:%20sara.yeo@utah.edu).

**Academic misconduct.** **Academic misconduct will be punished to the fullest extent possible**. You are responsible for understanding what constitutes academic misconduct (see [Policy 6-400](http://regulations.utah.edu/academics/6-400.php)). Anyone found guilty of academic misconduct should expect to fail this course. In addition, academic misconduct may result in other penalties deemed appropriate by the university. Your rights and responsibilities are outlined in Policy 6-400, the Code of Student Rights and Responsibilities. You are responsible for obeying [Policy 6-400](http://regulations.utah.edu/academics/6-400.php). Ignorance of the policy is not an excuse.

**Emergency plan.** In the event of a University-wide emergency which prevents us from meeting, you should continue to stay current with our schedule as posted in this syllabus and to attend to the course website on Canvas. Information about the status of assignments and other course work due during this period will be addressed on Canvas and by way of email. **It is critical that you check your University email account frequently**.

**Accommodations.** Curriculum accommodations take two forms---scheduling and content accommodations. **There will be no content accommodations in this course**. The material has been selected for its pedagogical value in relation to the concepts we are engaging. It is your responsibility to review the course materials to be sure that this is a course you wish to take. More information on the University's accommodation policy can be found in [Policy 6-100](https://regulations.utah.edu/academics/6-100.php).

# University Policies

**COVID-19.** If you test positive for COVID-19, please submit a report at [coronavirus.utah.edu](https://coronavirus.utah.edu). For more information about how the University is handling the coronavirus pandemic, visit [coronavirus.utah.edu](https://coronavirus.utah.edu).

**ADA.** The University of Utah seeks to provide equal access to its programs, services, and activities for people with disabilities. If you will need accommodations in this class, reasonable prior notice needs to be given to the Center for Disability Services, 162 Olpin Union Building, (801) 581-5020. CDS will work with you and the instructor to arrange accommodations. All written information in this course can be made available in an alternative format with prior notification to the [Center for Disability Services](https://disability.utah.edu/).

**Safety.** The University of Utah values the safety of all campus community members. To report suspicious activity or to request a courtesy escort, call campus police at 801-585-COPS (801-585-2677). You will receive important emergency alerts and safety messages regarding campus safety via text message. For more information regarding safety and to view available training resources, including helpful videos, visit [safeu.utah.edu](http://safeu.utah.edu/).

Title IX makes it clear that violence and harassment based on sex and gender (includes sexual orientation and gender identity/expression) is a civil rights offense subject to the same kinds of accountability and the same kinds of support applied to offenses against other protected categories such as race, national origin, color, religion, age, status as a person with a disability, veteran's status or genetic information. If you or someone you know has been harassed or assaulted, you are encouraged to report it to the Title IX Coordinator in the Office of Equal Opportunity and Affirmative Action, 135 Park Building, 801-581-8365, or the Office of the Dean of Students, 270 Union Building, 801-581-7066. For support and confidential consultation, contact the Center for Student Wellness, 426 SSB, 801-581-7776. To report to the police, contact the Department of Public Safety, 801-585-2677 (COPS).

Responsible employees and campus security authorities (CSAs) have different obligations. Responsible employees are defined by Title IX and CSAs are defined under the Clery Act. Though certain people/positions may be both, the concepts and requirements are different. On our campus, responsible employees are required to report any information about possible sexual misconduct or discrimination to the OEO/AA. CSAs are required to report crimes that occurred on campus to campus police.

Responsible employees are university employees, including students in paid leadership positions, who are required to report sexual misconduct to the Office of Equal Opportunity and Affirmative Action per university regulations. Examples of responsible employees include:

-   Professors and other faculty
-   Administration and staff (non-mental health)
-   Resident advisers
-   Student employees
-   Campus police or campus security officials
-   Athletic coaches/assistants

Campus security authorities are university employees who have significant responsibility for student and campus activities, including but not limited to student housing, student discipline and campus judicial proceedings and are designated to receive and report criminal incidents to the University of Utah Police Department.

**Undocumented Student Support.** Immigration is a complex phenomenon with broad impact---those who are directly affected by it, as well as those who are indirectly affected by their relationships with family members, friends, and loved ones. If your immigration status presents obstacles to engaging in specific activities or fulfilling specific course criteria, confidential arrangements may be requested from the Dream Center. Arrangements with the Dream Center will not jeopardize your student status, your financial aid, or any other part of your residence. The Dream Center offers a wide range of resources to support undocumented students (with and without DACA) as well as students from mixed-status families. To learn more, please contact the Dream Center at 801-213-3697 or visit [dream.utah.edu](http://dream.utah.edu/).

# Course Schedule

## Week 1 (11-Jan): Introduction

Readings

-   Syllabus

## Week 2 (18-Jan): (Quantitative) Communication Research

Discussant:

Readings

-   Kerlinger, F. N. (1986b). Science and the Scientific Approach. In *Foundations of Behavioral Research* (3rd edition, pp. 3--13). Holt, Rinehart and Winston.
-   Smith, J. K. (1983). Quantitative versus qualitative research: An attempt to clarify the issue. *Educational Researcher*, *12*(3), 6--13. <https://doi.org/10.3102/0013189X012003006>

## Week 3 (25-Jan): Communication as Social Science

Discussant:

Readings

-   Calhoun, C. (2011). Communication as social science (and more). *International Journal of Communication*, *5*, 1479-1496.
-   Donsbach, W. (2006). The identity of communication research. *Journal of Communication*, *56*(3), 437--448. [https://doi.org/10.1111/j.1460-2466.2006.00294.](https://doi.org/10.1111/j.1460-2466.2006.00294.x)
-   Eveland, Jr., W. P. (1997). Interactions and nonlinearity in mass communication: Connecting theory and methodology. *Journalism & Mass Communication Quarterly*, *74*(2), 400--416. <https://doi.org/10.1177/107769909707400211>
-   McLeod, J. M., Kosicki, G. M., & Pan, Z. (1991). On Understanding and Misundertanding Media Effects. In J. Curran & M. Gurevitch (Eds.), *Mass Media and Society* (pp. 235--266). Edward Arnold.

## Week 4 (1-Feb): From an Idea to a Research Project

Discussant:

Readings

-   Kerlinger, F. N. (1986a). Research Design: Purpose and Principles. In *Foundations of Behavioral Research* (3rd edition, pp. 279--291). Holt, Rinehart and Winston.
-   McLeod, J. M. (1998a). *Concept Explication and Theory Construction Part I: Meaning Analysis*.
-   McLeod, J. M. (1998b). *Concept Explication and Theory Construction Part II: Empirical Analysis*.

## Week 5 (8-Feb): Survey Research

Discussant:

Readings

-   Marsh, C. (1982). *The Survey Method: The Contribution of Surveys to Sociological Explanation*. Allen & Unwin.
-   Krosnick, J. A. (1999). Survey research. *Annual Review of Psychology*, *50*(1), 537--567. <https://doi.org/10.1146/annurev.psych.50.1.537>

## Week 6 (15-Feb): Measurement, Variables, Reliability & Validity

Discussant:

Readings

-   

## Week 7 (22-Feb): Sampling

Discussant:

Readings

-   asd

## Week 8 (1-Mar): Experiments

Discussant:

Readings

-   

## Week 9 (8-Mar): SPRING BREAK

No class

## Week 10 (15-Mar): Data Reduction & Scaling

Discussant:

Readings

-   asdas

## Week 11 (22-Mar): Data Analysis

Discussant:

Readings

-   

## Week 12 (29-Mar): Data Analysis

Discussant:

Readings

-   

## Week 13 (5-Apr): Data Analysis / Writing Workshop

## Week 14 (12-Apr): Data Analysis / Writing Workshop

## Week 15 (19-Apr): Data Analysis / Writing Workshop
