---
title: "Data Analysis Assignment 4"
subtitle: "COMM 7370 | Spring 2026"
format:
  pdf:
    geometry: 
      - top=.75in
      - left=.8in
      - right=.8in
    urlcolor: blue
  html:
    code-fold: true
    toc: true
    theme: sandstone
---

In this assignment, you will use the Trust in Science and Science-Related Populism (TISP) dataset, available on OSF (see details in paper), to answer a research question of your design and choosing. 

For reference, these data were used in the following paper:

> Mede, N. G., Cologna, V., Berger, S., C. Besley, J., Brick, C., Joubert, M., W. Maibach, E., Mihelj, S., Oreskes, N., S. Schäfer, M., van der Linden, S., Abdul Aziz, N. I., Abdulsalam, S., Abu Shamsi, N., Aczel, B., Adinugroho, I., Alabrese, E., Aldoh, A., Alfano, M., … Zwaan, R. A. (2025). Public communication about science in 68 countries: global evidence on how people encounter and engage with information about science. *Science Communication*, 10755470251376615. https://doi.org/10.1177/10755470251376615

Start by familiarizing yourself with the data (you might start by selecting a country or countries of interest). Then, come up with a research question of hypothesis that can be addressed by these data. Conduct your analysis to address your research question or hypothesis.^[You can have multiple research questions and/or hypotheses.] 