---
title: |
  | COMM 3710: Intro to Quantitative Research
pagetitle: COMM 3710 syllabus
format: 
   html:
      toc: true
      toc_float: true
      theme: simplex
      smooth-scroll: true
      embed-resources: true
   pdf:
      documentclass: article
      toc: false
      colorlinks: true
urlcolor: blue
---

Instructor: [Dr. Sara K. Yeo](https://faculty.utah.edu/~sarakyeo)

Email: [sara.yeo@utah.edu](mailto:sara.yeo@utah.edu)


# Course Outline {#sec-outline}

This course is a basic research methods course for those with little or no experience or course work in quantitative communication research. COMM 3710 is a quantitative intensive (QI) course. The goal of this course is to provide you with a critical framework for evaluating social science research and some hands-on experience in the process of conducting empirical investigations.

We will examine how research questions are developed into a research project. Additionally, we will learn how to select appropriate research techniques, measure concepts, draw samples, interpret results, and communicate our research.

Key topics include:

* Formalizing hypotheses and research questions grounded in theory
* Testing hypotheses and research questions
* Conceptual and operational definitions
* Measurement, sampling, and research design
* Data analysis in communication research

::: {.callout-note}
You are expected to log into the course Canvas website regularly (**at least 3-5 times per week**), complete and submit work on time, and ask questions if you need help. **It is your responsibility as a student to ask questions in a timely manner during scheduled labs and office hours, if you need help.**
:::

---

# Teaching Assistants and Lab Sections {#sec-ta}
There is one graduate teaching assistant (TA) in this course. The graduate TA is responsible for leading the lab sections. For lab attendance policies, review the [course requirements](@sec-requirements).

There are two lab sections associated with this course:

- Section 002 (Wed 9:40 - 10:30 am, GC 1770)
- Section 003 (Wed 10:45 - 11:35 am, GC 1570)

Graduate TA: Jasim Uddin

Email: [u1468782@utah.edu](mailto:u1468782@utah.edu)

Office hours: Fri 1-3 pm, LNCO XXXX

---

# Required Text and Readings {#sec-text}

Two books are required for this course. Both are available online. The course fee that you paid when you enrolled covers Inclusive Access to the Wrench textbook via Canvas.

> Wrench, J.S. (2019) *Quantitative Research Methods for Communication: A Hands-On Approach* (4th edition). New York, NY: Oxford University Press.

- To access this textbook, navigate to your **Bookshelf** on the Canvas site for this course.
- This textbook is available through the [Inclusive Access program](https://www.campusstore.utah.edu/inclusiveaccess/), which provides you with digital access to the textbook via Canvas at a reduced price.
- You may opt out of the Inclusive Access program [here](https://www.campusstore.utah.edu/inclusiveaccess/). However, the textbook is **required**, and you are expected to have it, even if you opt out of this program.

> Yeo, S. K. & Y. Sun (2021) [*COMM 3710: Getting Started with R*](https://sarakyeo.github.io/COMM-3710-bookdown/docs/index.html).

- This book is free and accessible via the link provided on Canvas.

Additional readings will be provided as PDF documents on Canvas.

---

# Course Requirements {#sec-requirements}
