---
title: |
  | COMM 3710: Data Analysis
pagetitle: "COMM 3710: Week 13"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
urlcolor: blue
---

# General Steps to Analyze Data
1. Manage data
   - Frequency distributions
   - Recoding data
   - Creating composite or secondary variables
2. Hypothesis testing (review Week 9: Inferential Statistics, if necessary)
   - $\chi^2$ test of independent
   - $t$-test
   - One-way analysis of variance (ANOVA)
   - Pearson's correlation

At this point in the course, you will have conducted most of these steps in data analysis through your individual lab assignments and even in your group project assignments. Review the videos and resources embedded in your lab assignments and group projects.

Other resources for using R and RStudio for data analysis can be found in the [COMM 3710: Getting Started with R book](https://sarakyeo.github.io/COMM-3710-bookdown/docs/index.html).

Remember that you have done most, if not all, the steps of data analysis in your individual assignments. Be sure to refer to your R code from previous assignments as necessary.

---

# Managing Data
To manage your data, you should <mark>**run frequency distributions**</mark>, and <mark>**recode and create variables as necessary**</mark>.

We learned how to do this in various lab assignments. Review your R code submissions to these assignments and the assignments themselves.

## What You Already Know from Lab Assignments
From your lab assignments, you already know how to:

- [LA-4](https://sarakyeo.github.io/COMM-3710/LA/LA-4.html)
   - Read/Load data into R.
   - Use the pipe operator, `%>%`.
   - Select variables from a data frame using the `select()` function.
   - Filter cases from a data frame using the `filter()` function.
   - Summarize variables using the `summarise()` function. you can also use the `descr()` function here.
- [LA-5](https://sarakyeo.github.io/COMM-3710/LA/LA-5.html) and [LA-6](https://sarakyeo.github.io/COMM-3710/LA/LA-6.html)
   - Run and examine frequency distributions using the `freq()` function in the `summarytools` package.
   - View descriptive statistics using the `descr()` function in the `summarytools` package.
   - Recode variables using the `case_when()` function.
   - Create new variables from existing variables in a data frame using the `mutate()` function.
- [LA-7](https://sarakyeo.github.io/COMM-3710/LA/LA-7.html)
   - Create graphs using the `ggplot2` package.

---

# Hypothesis Testing {.tabset .tabset-fade}
In this step, we will conduct statistical hypothesis testing. In other words, we will assess empirical evidence and determine whether we can reject our null hypothesis. If necessary, review content from [Week 12](https://sarakyeo.github.io/COMM-3710/week12.html).

Then, watch the video below about hypothesis testing.

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/08uylSp-CuI" frameborder="0" data-external="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
<br>

In Week 12, we discussed three statistical tests that we can use in hypothesis testing. The videos below show you some other ways of conducting each of these tests using R.

- [Chi-square ($\chi^2$) test of independence](https://youtu.be/Dnlp9vswwEk)
- [Independent samples $t$-test](https://youtu.be/ANMuuq502rE?t=416)
- [One-way analysis of variance](https://youtu.be/2uQCUBtqCfM) (ANOVA)
- [Correlation](https://youtu.be/lf4HfHx2ASs)

> There are also hints on how to select and conduct statistical tests in R in LA-8.

---

# A Note on Data Analysis
The videos shared here are just one of many ways to manage data and conduct statistical tests. With R, there are many ways to achieve the same goal.

Because R is open-source software, packages are continuously being developed by people all over the world. You are welcome to use these packages but they will not be taught in this course.

<mark>If you **do** use another package, ensure that the answers you get from using it are correct by checking them with the strategies shown in this course.</mark>