---
title: |
  | <a name="top"></a>
  | COMM 3710: Data Analysis
pagetitle: "COMM 3710: Week 10"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# General Steps to Analyze Data
1. Manage data
   - Frequency distributions
   - Recoding data
   - Creating composite or secondary variables
2. Hypothesis testing (review Week 9: Inferential Statistics, if necessary)
   - $\chi^2$ test of independent
   - $t$-test
   - One-way analysis of variance (ANOVA)
   - Pearson's correlation

At this point in the course, you will have conducted most of these steps in data analysis through your individual lab assignments and even in your group project assignments. Review the videos and resources embedded in your lab assignments and group projects.

Other resources for using R and RStudio for data analysis can be found in the [COMM 3710: Getting Started with R book](https://sarakyeo.github.io/COMM-3710-bookdown/docs/index.html).

Remember that you have done most, if not all, the steps of data analysis in your individual assignments. Be sure to refer to your R code from previous assignments as necessary.

<a href="#top">Back to top</a>

# Managing Data
To manage your data, you should run frequency distributions, and recode and create variables as necessary.

Watch the videos below to refresh your memory on conducting the functions in R:

- [Running frequency distributions](https://youtu.be/Dbj_l1PRIjA?t=697)
- [Recoding data](https://youtu.be/b9Bh3K5bi0I)
   - [Reverse coding](https://youtu.be/b9Bh3K5bi0I?t=725)
- [Creating composite or secondary variables](https://youtu.be/b9Bh3K5bi0I?t=994)


# Hypothesis Testing
In this step, we will conduct statistical hypothesis testing. In other words, we will assess empirical evidence and determine whether we can reject our null hypothesis. If necessary, review content from [Week 9](https://sarakyeo.github.io/COMM-3710/week9.html).

Then, watch this [video](https://youtu.be/08uylSp-CuI) about hypothesis testing.

In Week 9, we discussed three statistical tests that we can use in hypothesis testing. The videos below show you how to conduct each of these tests using R.

- [Chi-square ($\chi^2$) test of independence](https://youtu.be/Dnlp9vswwEk)
- [Independent samples $t$-test](https://youtu.be/ANMuuq502rE?t=416)
- [One-way analysis of variance](https://youtu.be/2uQCUBtqCfM) (ANOVA)
- [Correlation](https://youtu.be/lf4HfHx2ASs)

<a href="#top">Back to top</a>

# A Note on Data Analysis
The videos shared here are just one of many ways to manage data and conduct statistical tests. With R, there are many ways to achieve the same goal.

Because R is open-source software, packages are continuously being developed by people all over the world. You are welcome to use these packages but they will not be taught in this course. If you **do** use another package, ensure that the answers you get from using it are correct by checking them with the strategies shown in this course.

<a href="#top">Back to top</a>