---
title: 'LA-6: Examining and Managing Data (10 points)'
pagetitle: "COMM 3710: LA-6"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
urlcolor: blue
---

```{r setup, include=FALSE}
library(tidyverse)
library(summarytools)
hdata <- read.csv("HELP.csv")
knitr::opts_chunk$set(echo = FALSE)
```

In this assignment, you will put the skills you learned in LA-5 into practice.

Remember to ...

1) Set up your R script appropriately.
2) Include a comment for each line of code in your R script. This can be pseudocode or other comments.

---

# Step 1 {.tabset .tabset-fade}
## Instructions
Load the following packages in your current session of R:

- `tidyverse`
- `summarytools`

Read the [HELP](https://utah.instructure.com/files/117853074/download?download_frd=1) data set into R. Use the codebook to familiarize yourself with the variables in the data set.

## Codebook

| Variable Name | Description |
| :------------ | :---------- |
| `age` | Subject age at baseline |
| `anysub` | Use of any substance post-detox (no, yes) |
| `cesd` | Center for Epidemiologic Studies Depression measure at baseline (high scores indicate more depressive symptoms) |
| `d1` | Lifetime number of hospitalizations for medical problems (measured at baseline) |
| `daysanysub` | Time (in days) to first use of any substance post-detox |
| `dayslink` | Time (in days) to linkage to primary care |
| `drugrisk` | Risk Assessment Battery drug risk scale at baseline |
| `e2b` | Number of times in past 6 months entered a detox program (measured at baseline) |
| `female` | Biological sex (0 = male, 1 = female) |
| `sex` | Biological sex (male, female)  |
| `g1b` | Experienced serious thoughts of suicide in last 30 days (measured at baseline; no, yes) |
| `homeless` | Housing status (housed, homeless) |
| `i1` | Average number of drinks consumed per day in past 30 days (measured at baseline) |
| `i2` | Maximum number of drinks consumed per day in past 30 days (measured at baseline) |
| `id` | Subject identifier |
| `indtot` | Inventory of Drug Use Consequences (InDUC) total score (measured at baseline) |
| `linkstatus` | Post-detox linkage to primary care (0 = no, 1 = yes) |
| `link` | Post-detox linkage to primary care (no, yes) |
| `mcs` | SF-36 Mental Component Score (measured at baseline; lower scores indicate worse status) |
| `pcs` | SF-36 Physical Component Score (measured at baseline; lower scores indicate worse status) |
| `pss_fr` | Perceived social support by friends (measured at baseline; higher scores indicate more support) |
| `racegrp` | Race/Ethnicity (black, hispanic, white, other) |
| `satreat` | Any BSAS substance abuse treatment at baseline (no, yes) |
| `sexrisk` | Risk Assessment battery; sex risk score (measured at baseline; high scores indicates higher risk) |
| `substance` | Primary substance of abuse (alcohol, cocaine, heroin) |
| `treat` | Randomized to HELP clinic (no, yes) |


# Step 2 {.tabset .tabset-fade}
## Instructions
Patients with a mental component score (`mcs`) less than 20 are thought to be at extreme risk of returning to the detoxification unit within the next 12 months.

Make a new variable called `ExtremeMCS` and code it as `1` if a patient is at risk based on his/her mcs score and `0` otherwise. Then, answer the following questions.

a) How many patients are thought to be at high risk of returning to the detoxification unit within the next 12 months?
b) What percentage of patients are at low risk of returning to the detoxification unit within the next 12 months?

## Hint
Review LA-5 and how to use the `mutate()` and `case_when()` commands.


# Step 3
Make a new variable `SuicidalThought` based on the variable `g1b`. Have `1` indicate a patient has had suicidal thoughts and a `0` indicate they have not.

a) How many patients report having had suicidal thoughts?


# Step 4 
Make a new variable `HomelessStatus` based on the variable `homeless`. Have `1` indicate that a patient is homeless and `0` indicate that they are housed.

a) What percentage of patients are homeless?


# Step 5
Suppose we want to assess the overall risk of a patient and `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus` are considered risk factors. Construct a new variable called `RiskTotal` that quantifies the number of risk factors for each patient. That is, make it a sum of these 3 variables.

a) What percentage of patients in the study have fewer than 3 risk factors?


# Submission
Submit your R script (`LA-6_FirstName-LastName.R`) to Canvas.

Your R script should:

1) Include code to install and load the packages.
2) Include code to set your working directory.
3) Contain comments and/or pseudocode for every single line of R code.
4) Run in its entirety without errors.

To ensure that your R script runs without errors, you should:

- Save your script.
- Completely shut down RStudio or restart your R session.
- Reopen RStudio, open your `LA-6_FirstName-LastName.R` script.
- Run the entire script by clicking the "Run" button in the top right of the R script.

> These standards apply to all submissions in this course that require R scripts.
