---
title: "LA-6: Data Visualization (15 points)"
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - left=20mm
         - right=20mm
         - heightrounded
      toc: false
      colorlinks: true
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(summarytools)
library(rstatix)
library(kableExtra)
library(formatR)

# Read data into R
wind <- read_csv("wind-turbines.csv")

```

# Learning Outcomes

In this assignment, you will learn how to:

-   Run and examine frequency distributions using the `freq()` function in the `summarytools` package.
-   View descriptive statistics using the `descr()` function in the `summarytools` package.
-   Recoding variables using the `case_when()` function.
-   Create new variables from existing variables in a data frame using the `mutate()` function.

::: callout-tip
Read all the instructions carefully before starting the assignment.
:::

------------------------------------------------------------------------

# Instructions



------------------------------------------------------------------------

# Submission

Submit your R script (named `LA-#_FirstName-LastName.R`) to Canvas.

Your R script should:

1)  Include commands and functions that are necessary to address all the questions in the assignment.
2)  Contain comments that answer the questions in the assignment.
3)  Run in its entirety without errors.

To ensure that your R script runs without errors, you should:

-   Save your script.
-   Navigate back to Your Workspace on Posit Cloud.
-   Reopen your project.
-   Run the entire script line-by-line without editing it to ensure there are no errors.

::: callout-important
These standards apply to all submissions in this course that require R scripts. You should follow these instructions for preparation, naming, and saving of your R script for all of your individual lab assignments.
:::
