---
title: 'LA.4: Working with Data (10 points)'
pagetitle: "COMM 3710: LA.4"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# Resources
- Before starting this assignment, watch this [video](https://youtu.be/b9Bh3K5bi0I). Once again, keep this link handy as you may need to watch the video several times to complete the assignment.
- Additional resources for R can be found [here](https://rpubs.com/yesun/652965).

> Try to answer/solve these problems using the resources above before resorting to the hints in the assignment. 

> Attempting to figure out R code that gives you the correct result (you can always check your result using the hints) is the best way to learn this material and will have long-term benefit.

---

# Instructions
1. Load in the [HELP data set](https://utah.instructure.com/files/108105219/download?download_frd=1) from [LA.3](https://sarakyeo.github.io/COMM-3710/LA/LA.3.html). If necessary, review the codebook (explanation of variables) in [LA.3](https://sarakyeo.github.io/COMM-3710/LA/LA.3.html).
<details>
<summary>Hint</summary>

   If necessary, review how you loaded the data in LA.3. Remember that you can name this object anything you like.
</details>
<br>

2. Patients with a mental component score (`mcs`) less than 20 are thought to be at extreme risk of returning to the detoxification unit within the next 12 months. Make a new variable called `ExtremeMCS` and code it as 1 if a patient is at risk based on his/her mcs score and 0 otherwise.
<details>
<summary>Hint</summary>
   In addition to the method shown in the video, you can create this new variable using the `ifelse` command.
   
   Figure out what the arguments (the text and numbers within the parentheses) in the `ifelse` function mean by typing `?ifelse` into the Console in RStudio and reading the documentation.
      <details>
      <summary>If you need another hint...</summary>
      Try...`helpdata$ExtremeMCS <- ifelse(helpdata$mcs < 20, 1, 0)`
      </details>
   </details>
<br>

3. Make a new variable `SuicidalThought` based on the variable `g1b`. Have 1 indicate a patient has had suicidal thoughts and a 0 indicate they have not. 
<details>
<summary>Hint</summary>
   You can use the same logic (and command) that you used in Q2 to create this variable.
</details>
<br>

4. Make a new variable `HomelessStatus` based on the variable `homeless`. Have 1 indicate that a patient is homeless and 0 indicate that they are housed.

<br>

5. Suppose we want to assess the overall risk a patient has to return to the detoxification unit and `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus` are considered risk factors. Construct a new variable called `RiskTotal` which computes the number of risk factors a particular patient has. That is, make it a sum of these 3 variables.
<details>
<summary>Hint</summary>
   You want to create a new variable called `RiskTotal`, which is the sum of `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus`. First, try the most straightforward way, which is to use this general formula:
   ```
   Dataframe$NewVariable <- Dataframe$Var1 + Dataframe$Var2 + Dataframe$Var3 
   ```
   <details>
   <summary>For more...</summary>
      Like most things in R, there are many other ways to do this. One way is to transform the data using the command, `transform`. Get help with `transform` by typing `?transform` into the Console and reading the documentation.
         <details>
         <summary>Need help with `transform`?</summary>
         Try... `helpdata <- transform(helpdata, RiskTotal = ExtremeMCS + SuicidalThought + HomelessStatus)`
         </details>
   </details>

<br>

6. Make frequency tables of `ExtremeMCS`, `SuicidalThought`, and `RiskTotal`.
      a. How many patients are thought to be at risk based on their `mcs` score? <!--91-->
      b. What percentage of patients have experienced suicidal thoughts? <!--28.0%-->
      c. What percentage of patients in the study have fewer than 3 risk factors? <!--94.9%-->

   <details>
   <summary>Hint</summary>

      Refer to LA.3 to review creating frequency tables.
   </details>
<br>

7. Submit the following on Canvas:
   (a) A **.R file** containing the code used to complete this assignment. This document should include comments that explain your commands.
   (b) A **PDF file** containing the answers to each question--clearly label the answers with the question number.