---
title: "LA.5: Visualizing Data (10 points)"
pagetitle: "COMM 3710: LA.5"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# Resources{#resources}
In this assignment, we will learn how to use the R package, `ggplot2` to create graphs. Before you begin the assignment, watch and familiarize yourself with the following videos. Remember to drop in to virtual office hours if you need help.

- Watch [Video 06](https://youtu.be/mwLyXHfCPdE) about graphing one variable at a time in R. 
- Watch [Video 07](https://youtu.be/IZoCbCQRmUE) about graphinc relationships in R.

As always, keep the videos handy for reference as you work through this assignment.

---

# Data
Use the [Utilities.csv](https://utah.instructure.com/files/108105204/download?download_frd=1) data set to complete this assignment. This data set contains a random sample of 117 utility bills for the following variables:

* `month`: month (coded as a number)
*	`day`: day of month on which bill was calculated
*	`year`: year of bill
*	`temp`: average temperature ($^{\circ}$F) for billing period
*	`kwh`: electricity usage (kwh)
*	`ccf`: gas usage (ccf)
*	`thermsPerDay`: a numeric vector
*	`billingDays`: number of billing days in billing period
*	`totalbill`: total bill (in dollars)
*	`gasbill`: gas bill (in dollars)
*	`elecbill`: electric bill (in dollars)
*	`notes`: notes about the billing period
*	`donate`: (yes or no) did the person add money to their bill to be donated to Operation Fuel, a charity providing heat to families/small businesses in need

---

## Instructions
1. Import the [Utilities.csv](https://utah.instructure.com/files/108105204/download?download_frd=1) data set. Use the codebook above to familiarize yourself with the variables.
<details>
<summary>Hint</summary>

   Review LA.3 or LA.4 for the command to read the data into a dataframe.
</details>
<br>

2. Make a graph to display the distribution of customers' total monthly bill (include the graph in your submission) and answer the following question.
   a. Use the histogram you created and describe the distribution. Is the distribution skewed or symmetric (see Wrench Ch. 14: Skewness and Kurtosis for an explanation of skewness or watch Video 06 starting at 14:02)? If skewed, is the distribution skewed right or left? At what cost do most of the total monthly bills fall?
   <!--Slightly positively (right) skewed, most total monthly bills are between $100 and $150-->
   <details>
   <summary>Hint</summary>
   
      To create a histogram, watch Video 06. The `ggplot2` commands you will use are: `ggplot()` and `geom_histogram()`. Remember that you can also read the documentation for these commands by typing `?ggplot` and `?geom_histogram` in the Console.
   </details>
<br>

3. Make a scatter plot to display gas bill by month (include the graph in your submission).
<details>
<summary>Hint</summary>
   
   Watch Video 07 to learn how to make a scatter plot. The commands you will use are `ggplot()` and `geom_point()`.
</details>
      a. Based on your graph, which month do you think has the highest **average** gas bill?
      b. Calculate the average gas bill for the months of January and December. Which is higher?
      <details>
<summary>Hint</summary>
      To calculate the average gas bill for January, first filter the data to contain only observations from January (i.e., `month == 1`). To do this, create an object that filters the `utilities` dataframe by month. You could, for example, use the code:`jan <- filter(utilities, month == 1)`. For help with the `filter` function, type `?filter` into your Console window.
      
         Then, you can use the `mean()` function to calculate the average gas bill for that month. Type `?mean` into the Console and read the documentation for this function. Remember to strip NA values from your computation by using the argument, `na.rm = TRUE`.
</details>
<br>

4. Make a graph to display electric bill by month (include the graph in your submission).
      a. Based on your graph, which month do you think has the highest **average** electric bill?
      b. Calculate the average electric bill for the months of September and December. Which is higher?

<br>

5. Make a graph to display the relationship between gas usage and gas bill (include the graph in your submission). 
      a. Does there appear to be a relationship between gas usage and gas bill? <!--Yes-->

<br>

6. Make a graph to display the relationship between electricity usage and electric bill (include the graph in your submission).
      a. Does there appear to be a relationship between electricity usage and electric bill? <!--Yes-->

<br>

7. Create a new categorical variable called `season`. Have the variable equal winter if the bill was from December, January, or February. Have the variable equal spring if the bill was from March, April, or May. Have the variable equal summer if the bill was from June, July, or August. Have the variable equal fall if the bill was from September, October, or November.
<details>
<summary>Hint</summary>

   Use the skills you learned in data management (e.g., subsetting) to create a new variable called `season` according to the instructions. Then, use the command `freq(utilities$season)` from the `descr` package to check that you have created the `season` variable correctly.
</details>
<br>

8. Make a new variable, `DonorStatus`. Set `DonorStatus` equal to 1 if the billee donated money to *Operation Fuel* and 0 otherwise. 
<details>
<summary>Hint</summary>

   Review the `ifelse` command used in LA.4. 
</details>
<br>

9. Make a bar chart to display the count or proportion of donors by season (include the graph in your submission). Order the seasons from lowest proportion of donors to highest proportion of donors; answer the question below.
   a. Does there seem to be a relationship between season and donation?
   <details>
   <summary>Hint</summary>
      
      Watch Video 07, which covers creating bar charts with `ggplot2`. You will use the `ggplot()` and `geom_bar()` commands.
      
      <details>
      <summary>Stuck? Click here.</summary>
      
         *Note*: The `ggplot2` command shown at 12:45 may be giving you an error. If so, try the code below:
         
         ```
         data.plot <- na.omit(utilities[ , c("season", "DonorStatus")])
         data.plot$DonorStatus <- as.character(data.plot$DonorStatus)
         ggplot(data = data.plot) +
               geom_bar(aes(x = season, fill = DonorStatus))
         ```
      </details>
</details>
<br>

10. Submit the following on Canvas:
      a. A **.R file** containing the code used to complete this assignment. This document should include comments that explain your commands.
      b. A **PDF file** containing the answers/figures/tables to each question--clearly label the answers with the question number.
