---
title: "LA.8: Practice Data Analysis (10 points)"
pagetitle: "COMM 3710: LA.8"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# Resources
Video resources for data analysis with R:

1. [Hypothesis testing](https://youtu.be/08uylSp-CuI)
2. [Analysis of variance (ANOVA)](https://youtu.be/2uQCUBtqCfM)
3. [Chi-square test of independence](https://youtu.be/Dnlp9vswwEk)
4. [Correlation](https://youtu.be/lf4HfHx2ASs)

Remember that help with R is also available in the [R Help Guide](https://rpubs.com/yesun/Comm3710_helpwithR) and other resources available in the R Resources module on Canvas.

You may find the following R packages useful as you work through this assignment:

- `magrittr`
- `tidyverse`
- `descr`
- `rstatix`
- `Hmisc`

Additionally, you can refer back to hints from previous individual assignments:

- [LA.3](https://sarakyeo.github.io/COMM-3710/LA/LA.3.html)
- [LA.4](https://sarakyeo.github.io/COMM-3710/LA/LA.4.html)
- [LA.5](https://sarakyeo.github.io/COMM-3710/LA/LA.5.html)
- [LA.6](https://sarakyeo.github.io/COMM-3710/LA/LA.6.html)
- [LA.7](https://sarakyeo.github.io/COMM-3710/LA/LA.7.html)

---

# Data
You will use the [Ithaca.csv](https://utah.instructure.com/files/108105203/download?download_frd=1) data set for this assignment. These data were collected by students in a research methods course at Cornell University for teaching purposes.

A data frame with 465 observations on the following variables^[`99` = “Don’t know” unless otherwise specified]:

*	`tvinat`: Attention to international TV news (0 = “Little attention,” 10 = “Very close attention”)
*	`tvnaat`: Attention to national TV news (0 = “Little attention,” 10 = “Very close attention”)
*	`tvhardat`: Attention to TV news about politics and economy (0 = “Little attention,” 10 = “Very close attention”)
*	`tvsoftat`: Attention to soft news on TV (0 = “Little attention,” 10 = “Very close attention”)
*	`tvcrat`: Attention to TV crime dramas (0 = “Little attention,” 10 = “Very close attention”)
*	`tvcomat`: Attention to TV comedies (0 = “Little attention,” 10 = “Very close attention”)
*	`educ`: Highest year of school completed
*	`age`: Age of respondent
*	`marit`: Marital status (1 = “single,” 2 = “married,” 3 = “divorced/separated,” 4 = “widowed,” 5 = “other,” 9 = “Don’t know/NA”)
*	`sex`: 0 = “female,” 1 = “male”, 9 = "did not respond"

---

# Instructions
1. Familiarize yourself with the [Ithaca.csv](https://utah.instructure.com/files/108105203/download?download_frd=1) codebook above. Then, import/load the data set.

<br>

2. Conduct data management on these variables: `tvnaat`, `tvhardat`, `tvsoftat`, `sex`, `marit`.
      a. Recode values of `99` as `NA` in `tvnaat`, `tvhardat`, and `tvsoftat`.
      b. Currently, `sex` and `marit` are numeric variables (use `class()` or `typeof()` to convince yourself of this). Recode these variables as factors. Recode `sex` such that it has two levels, "female" and "male," and recode `marit` according to the levels currently assigned to the values in the codebook (i.e., "single," "married," "divorced," etc.).

<br>

3. Find the mean attention to national TV news for males and females.
      a. What is the mean attention to national TV news for women?
      b. What is the mean attention to national TV news for men?
      
<br>

4. Implement the appropriate statistical test to determine whether men spend significantly more time watching national TV news compared to women.
      a. What statistical test did you use?
      b. What is the value of the test statistic and the *p*-value?
      c. What conclusions can be drawn?

<br>

5. Implement the appropriate statistical test to determine whether there is a significant linear relationship between attention to national TV news and attention to news about politics and economy.
      a. What statistical test did you use?
      b. What is the value of the test statistic and the *p*-value?
      c. What conclusions can be drawn?

<br>

6. Implement the appropriate statistical test to determine whether attention to soft news varies significantly depending on marital status.
      a. What statistical test did you use?
      b. What is the value of the test statistic and the *p*-value?
      c. What conclusions can be drawn?

<br>

7. Submit the following on Canvas.
      a. A **.R file** containing the code used to complete this assignment. This document should include comments that explain your commands.
      b. A **PDF file** containing the answers to each question--clearly label the answers with the corresponding question number.