---
title: "In-class Assignment 2: Variables and Measurement (13 points)"
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - left=20mm
         - right=20mm
         - heightrounded
      toc: false
      colorlinks: true
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

Pick two of the concepts from the list below. You can also select one concept from the list below and come up with another concept in which you are interested. Using available library resources and databases, find journal articles that report empirical studies using your chosen concepts. Note that both concepts do not need to be in the same journal article/empirical study.

- Media use
- Political engagement
- Social capital
- Engagement with (media) content
- Support for a political party
- Opinions about climate change
- Sense of humor
- Opinions about energy
- Perceived credibility
- Trustworthiness

1) List the citation(s) of the journal articles in APA format.<!-- 2 points -->

2) For each concept, find and describe (in your own words) its working definition from the appropriate journal article. Be sure to cite the journal article in your answer.<!-- 3 pts -->

3) How was each concept operationalized in the journal article that you read?<!-- 2 pts -->

4) Using the operationalization that you described in Q3, identify:

   a) the level of measurement; <!-- 2 pts -->
   b) the attributes of the variable; <!-- 2 pts -->
   c) the values assigned to each attribute of the variable. <!-- 2 pts -->
   
5) For each variable, identify whether it was an independent or dependent variable in the study.<!-- 2 pts -->

Respond to each question using complete sentences. Clearly label your responses with the corresponding question number and check spelling and grammar in your submission. 

Submit your assignment as a PDF file via Canvas at the end of class.