---
title: "In-class Assignment 5: Content Analysis (12 points)"
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - left=20mm
         - right=20mm
         - heightrounded
      toc: false
      colorlinks: true
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

\vspace{-1cm}

**Objective:** To provide practical experience with content analysis.

**Submission:** Submit your completed assignment as an Excel spreadsheet on Canvas by the deadline (see Canvas assignment).

---

# Part 1: Finding our Codebook

We will be using a codebook from a journal article. Using library resources, find the following journal article:

> Coe, K., Kenski, K., & Rains, S. A. (2014). Online and uncivil? Patterns and determinants of incivility in newspaper website comments. *Journal of Communication, 64*(4), 658–679. [https://doi.org/10.1111/jcom.12104](https://doi.org/10.1111/jcom.12104)

**Table 1** in this journal article will serve as your codebook for this assignment. We will be coding our data for these five forms of incivility. The sample that you will code can be found on Canvas along with a coding sheet where you can record your codes.


# Part 2: Coding our Data

There is a sample of response posts taken from X (formerly Twitter). Individually code each posts for the five forms of incivility in Table 1. **Do not discuss your coding with others.**

Record your codes in the Excel spreadsheet (on Canvas).


# Part 3: Comparing your Codes

Once you have independently coded your data, compare your codes with other students in the course. You can do this via email or in-person during class. 

In the Excel file where you recorded your codes, write a reflection of this coding process. Your reflection should articulate the similarities and differences in your codes vs. others', as well as how and why you might code a particular post differently.

Your submission (Excel file) should include both your coded data and your reflection.