---
title: "In-class Assignment 6: Reporting Research (10 points)"
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - left=20mm
         - right=20mm
         - heightrounded
      toc: false
      colorlinks: true
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

\vspace{-1cm}

**Objective:** To gain experience reporting and reading research in an academic journal. 

**Submission:** Submit your completed assignment as a PDF on Canvas by the deadline (see Canvas assignment).

---

1) Every research project begins with searching for existing literature. Individual journal articles in the literature can serve as examples of how we report research. To report research effectively, we must read the primary literature.

> Yeo, S. K., Anderson, A. A., Becker, A. B., & Cacciatore, M. A. (2020). Scientists as comedians: The effects of humor on perceptions of scientists and scientific messages. *Public Understanding of Science, 29*(4), 408–418. [https://doi.org/10.1177/0963662520915359](https://doi.org/10.1177/0963662520915359)

2) Read the title and abstract of the article, then answer the following questions. Is this study a content analysis? If yes, explain why. If not, what kind of study is it?

3) Read the introduction of the paper. What are some of the "hooks" in the paper? What is the big picture?

4) Read the Method section. In your own words, explain how the sample was collected, who is in it, the variables measured, and how the data were analyzed.

5) Next, read the literature review. What existing topics in the literature are reviewed in the paper? Write a brief synopsis of each of the topics reviewed.

6) Read the results. List the results of the ANOVA reported in the article below. Then, interpret this result in your own words.

7) Read the discussion. List two limitations, one implication, and recommendations for future research from this study.

8) Proofread your qork before submitting it as a PDF on Canvas.


