---
title: 'GA.2: Data Management with SPSS and R'
pagetitle: "COMM 7800: GA.2"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
urlcolor: blue
---

```{r setup, include=FALSE}
library(tidyverse)
library(descr)
hdata <- read.csv("HELP.csv")
knitr::opts_chunk$set(echo = FALSE)
```

# Data

For this assignment, you will be working with the [Health Evaluation and Linkage to Primary Care (HELP) data set](https://utah.instructure.com/files/117538823/download?download_frd=1) again. As a reminder, the dataset is described again below.

The HELP study was a clinical trial for adult inpatients recruited from a detoxification unit. Patients with no primary care physician were randomized to receive a multidisciplinary assessment and a brief motivational intervention or usual care, with the goal of linking them to primary medical care.

The data set contains 453 observations on the following variables:

* `age`: Subject age at baseline (in years)
* `anysub`: Use of any substance post-detox (a factor with levels no yes)
* `cesd`: Center for Epidemiologic Studies Depression measure at baseline (high scores indicate more depressive symptoms)
* `d1`: lifetime number of hospitalizations for medical problems (measured at baseline)
* `daysanysub`: time (in days) to first use of any substance post-detox
* `dayslink`: time (in days) to linkage to primary care
* `drugrisk`: Risk Assessment Battery drug risk scale at baseline
* `e2b`: number of times in past 6 months entered a detox program (measured at baseline)
* `female`: 0 for male, 1 for female
* `sex`: a factor with levels male female
* `g1b`: experienced serious thoughts of suicide in last 30 days (measured at baseline; a factor with levels no yes)
* `homeless`: housing status: a factor with levels housed homeless
* `i1`: average number of drinks (standard units) consumed per day, in the past 30 days (measured at baseline)
* `i2`: maximum number of drinks (standard units) consumed per day, in the past 30 days (measured at baseline)
* `id`: subject identifier
* `indtot`: Inventory of Drug Use Consequences (InDUC) total score (measured at baseline)
* `linkstatus`: post-detox linkage to primary care (0 = no, 1 = yes)
* `link`: post-detox linkage to primary care: no yes
* `mcs`: SF-36 Mental Component Score (measured at baseline, lower scores indicate worse status)
* `pcs`: SF-36 Physical Component Score (measured at baseline, lower scores indicate worse status)
* `pss_fr`: perceived social support by friends (measured at baseline, higher scores indicate more support)
* `racegrp`: race/ethnicity: levels black hispanic other white
* `satreat`: any BSAS substance abuse treatment at baseline (no yes)
* `sexrisk`: Risk Assessment Battery sex risk score (measured at baseline)
* `substance`: primary substance of abuse (alcohol cocaine heroin)
* `treat`: randomized to HELP clinic (no yes)

---

# Instructions

## Step 1
Load the HELP dataset in R and SPSS.


## Step 2
Patients with a mental component score (`mcs`) less than 20 are thought to be at extreme risk of returning to the detoxification unit within the next 12 months.

Make a new variable called `ExtremeMCS` and code it `1` if a patient is at risk based on his/her mcs score and `0` otherwise.

a. How many patients are thought to be at extreme risk of returning to the detoxification unit within the next 12 months?


## Step 3
Make a new variable `SuicidalThought` based on the variable `g1b`. Have `1` indicate a patient has had suicidal thoughts and a `0` indicate they have not.

a. What percentage of patients have had suicidal thoughts?


## Step 4
Make a new variable `HomelessStatus` based on the variable `homeless`. Have `1` indicate that a patient is homeless and `0` indicate that they are housed.


## Step 5
Suppose we want to assess the overall risk a patient has to return to the detoxification unit and `ExtremeMCS`, `SuicidalThought`, and `HomelessStatus` are considered risk factors. Construct a new variable called `RiskTotal` which computes the number of risk factors for each patient. That is, make it a sum of these 3 variables.

Make a frequency table of the `RiskTotal` variable.

a. What percentage of patients in the study have fewer than 3 risk factors? 


## Step 6
For practice, we want to trichotomize the continuous variable, `sexrisk`. Suppose we want to split the variable evenly into three groups with respondents either in a low, medium, or high category depending on their `sexrisk` score. In other words, to start, we need to examine a frequency table to determine which variable values to include in the low, medium, and high categories. Once we have determined which variable values should be assigned to each category, we can recode the variable accordingly (give this new variable a name of your choice).

Note that it is easier to assign numbers to categorical data in SPSS. On the other hand, R can easily assign factors to categorical variables. In other words, the variable values of your recoded, three-category variable in SPSS will have numeric values while the same three-category variable in R can have character labels (instead of numbers).

a. How many patients are in the low sex risk category? Medium category? High?


## Submission
Submit a **.R file** (R script) and a **.sps file** (SPSS syntax) containing the following on Canvas:

- R and SPSS code/commands used to complete this assignment. Your R script and SPSS syntax should include annotations that explain your thought process as you work through the assignment.
- Clearly labeled answers to questions as comments/annotations in the R script and SPSS syntax.
