---
title: "GA.4: Practice Data Analysis"
pagetitle: "COMM 7800: GA.4"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
urlcolor: blue
---

# Data
You will use the [Ithaca.csv](https://utah.instructure.com/files/117605278/download?download_frd=1) data set for this assignment. These data were collected by students in a research methods course at Cornell University for teaching purposes.

A data frame with 465 observations on the following variables^[`99` = “Don’t know” unless otherwise specified]:

*	`tvinat`: Attention to international TV news (0 = “Little attention,” 10 = “Very close attention”)
*	`tvnaat`: Attention to national TV news (0 = “Little attention,” 10 = “Very close attention”)
*	`tvhardat`: Attention to TV news about politics and economy (0 = “Little attention,” 10 = “Very close attention”)
*	`tvsoftat`: Attention to soft news on TV (0 = “Little attention,” 10 = “Very close attention”)
*	`tvcrat`: Attention to TV crime dramas (0 = “Little attention,” 10 = “Very close attention”)
*	`tvcomat`: Attention to TV comedies (0 = “Little attention,” 10 = “Very close attention”)
*	`educ`: Highest year of school completed
*	`age`: Age of respondent
*	`marit`: Marital status (1 = “single,” 2 = “married,” 3 = “divorced/separated,” 4 = “widowed,” 5 = “other,” 9 = “Don’t know/NA”)
*	`sex`: 0 = “female,” 1 = “male”, 9 = "did not respond"

---

# Instructions

## Step 1
Familiarize yourself with the [Ithaca.csv](https://utah.instructure.com/files/108105203/download?download_frd=1) codebook above. Then, import/load the data set into R and SPSS.


## Step 2
Conduct data management on these variables: `tvnaat`, `tvhardat`, `tvsoftat`, `sex`, `marit`.
    
a. Recode the variables (i.e., create new variables from the existing ones) in `tvnaat`, `tvhardat`, and `tvsoftat` such that values of `99` become `NA` .
b. Currently, `sex` and `marit` are numeric variables. Recode these variables as factors. Recode `sex` such that it has two levels, "female" and "male" (all other values should be coded as `NA`), and recode `marit` according to the levels currently assigned to the values in the codebook (i.e., "single," "married," "divorced," etc.).


## Step 3
Find the mean attention to national TV news for males and females.

a. What is the mean attention to national TV news for women?
b. What is the mean attention to national TV news for men?
      

## Step 4
Implement the appropriate statistical test to determine whether men spend significantly more time watching national TV news compared to women.

a. What statistical test did you use?
b. What is the value of the test statistic and the *p*-value?
c. Report your results, including the conclusion that can be drawn from the hypothesis test, in APA format.


## Step 5
Implement the appropriate statistical test to determine whether there is a significant linear relationship between attention to national TV news and attention to news about politics and economy.

a. What statistical test did you use?
b. What is the value of the test statistic and the *p*-value?
c. Report your results, including the conclusion that can be drawn from the hypothesis test, in APA format.


## Step 6
Implement the appropriate statistical test to determine whether attention to soft news varies significantly depending on marital status.

a. What statistical test did you use?
b. What is the value of the test statistic and the *p*-value?
c. Report your results, including the conclusion that can be drawn from the hypothesis test, in APA format.


## Submission
Submit a **.R file** (R script) and a **.sps file** (SPSS syntax) containing the following on Canvas:

- R and SPSS code/commands used to complete this assignment. Your R script and SPSS syntax should include annotations that explain your thought process as you work through the assignment.
- Clearly labeled answers to questions as comments/annotations in the R script and SPSS syntax.