---
title: |
  | COMM 5117: Health Campaigns and Media
subtitle: |
  | Guidelines for Developing Campaign Planning Proposals
pagetitle: COMM 5117 group project
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - bottom=25mm
         - left=20mm
         - right=20mm
         - heightrounded
      papersize: letter
      toc: false
      colorlinks: true
urlcolor: blue
---

The overall assignment is to collaborate with your team to produce a research-based health communication campaign proposal. Here are some general guidelines for working on your proposal.

-   To produce your campaign, you will follow the Pink Book (National Cancer Institute, 2001).

> National Cancer Institute. (2001). *Making Health Communication Programs Work*. National Institutes of Health. <https://stacks.cdc.gov/view/cdc/24017>

-   You need to include a clean copy of focus group protocol and transcript in your appendix, along with any other relevant materials, if applicable.

-   Please collaborate respectfully with your team. Only under extreme circumstances will I consider altering groups, which have been randomly assigned.

# Elements of the Written Campaign Planning Proposal

1.  Preliminary research (10%)

    -   This will be conducted **before** you collect any research data for your campaign.

    -   Preliminary research should...

        -   assess the health or risk behavior or problem,

        -   identify all components of a possible solution,

        -   define clear communication objectives,

        -   define and learn about the intended audience,

        -   explore settings, channels, and activities best suited to reach the intended audience,

        -   develop a communication strategy for each intended audience,

        -   draft a communication plan.

2.  Research (10%)

    -   What were the goals of your focus group interviews?

    -   What strategies did you undertake? Briefly describe the focus group methodology.

        -   How were the focus group interviews conducted?

        -   What are the advantages of this method?

        -   What are the disadvantages?

        -   What was your sample size?

        -   What questions were asked?

    -   What other forms of research does your group feel a need to conduct to inform the campaign's objectives, strategies, or tactics?

3.  Analysis and results of research (20%)

    -   What did you find? Your analysis and results should be **tied directly** to your research goals.

        -   Reference your own focus group analysis about the campaign objectives, strategies, and tactics, etc.

        -   Describe in detail how you analyzed the focus group data.

        -   Describe in detail the insights drawn from the analysis of the focus group data.

4.  Proposed communication plan (35%)

    -   Your team must apply **at least one theory** to your communication plan.

    -   What do the theories employed tell us about effective campaign objectives and tactics?

        -   Who should you target?

        -   What should you tell them?

        -   Where should messages be placed?

        -   How will you execute each specific messaging tactic?

5.  Evaluation plan (5%)

    -   How will you know if your campaign worked?

    -   What kind of data will you need to collect to evaluate the effectiveness of your communication campaign?

    -   How will the data you collect tell you if your campaign worked? In other words, what are the metrics of success that you might look for in the data?

6.  Sample materials (10%)

    -   What will these materials look like?

    -   Create some mock-ups of your materials. They do not have to be polished or finished products, but should give us a sense of what the messages, tactics, products, etc. will look like.

7.  Other grading criteria (10%)

    -   Overall quality of written campaign planning proposal

        -   This includes grammar, writing quality, organization, flow, consistency, etc.

        -   Attach all your research materials including focus group protocols, transcription, analysis notes, etc.

    -   Innovation and creativity
