---
title: |
  | COMM 5117: Health Campaigns and Media
subtitle: |
  | Section 301
  |
  | Mondays - Fridays (9:00 am - 12:00 pm)
  | Location: University of Utah Asia Campus
  |
  | Professor: Dr. Sara K. Yeo
  | Email: [sara.yeo@utah.edu](mailto:sara.yeo@utah.edu)
pagetitle: COMM 5117 syllabus
format:
   pdf:
      documentclass: article
      geometry:
         - top=20mm
         - bottom=25mm
         - left=20mm
         - right=20mm
         - heightrounded
      papersize: letter
      toc: false
      colorlinks: true
urlcolor: blue
---

# Course Outline {#sec-outline}

This three-credit course provides an introduction to the application and integration of media effects theories in health and risk communication. We will examine social and cognitive models relevant to the context of health and risk communication campaigns and address theoretical perspectives that inform campaign messaging, including social determinants of health, individual behavior change, information processing, and message effects. Through this course, students will gain an understanding of theories relevant to the study of health and risk communication messages and an appreciation of the importance of integrating theory in understanding persuasive message effects.

::: callout-note
You are expected to log into the course Canvas website regularly (**at least 3-5 times per week**), complete and submit work on time, and ask questions if you need help. **It is your responsibility as a student to ask questions in a timely manner during scheduled labs and office hours, if you need help.**
:::

# Required Text and Readings {#sec-text}

There is no single textbook or edited volume that adequately captures the breadth and depth of this evolving area of research. Therefore, I have compiled readings for each week that will be available as PDF files unless they are directly available online.
There are several books that are relevant to this topic area. They are not required for this course, but may serve as good references.

* Rice, R. E., & Atkin, C. K. (2013). Public Communication Campaigns (R. E. Rice, Ed.; 4th ed.). Sage.

* du Pré, A. (2013). Communicating About Health: Current Issues and Perspectives (4th ed.). Oxford University Press.

# Technology Requirements {#sec-tech}

To ensure that you have full access to the course, you will need:

-   Reliable access to a laptop or desktop computer. A mobile device (tablet, phone) is not sufficient to complete this course. Please bring a laptop to lab.

-   An Internet browser compatible with [Canvas](https://utah.instructure.com/). For more information, see this [page](https://community.canvaslms.com/docs/DOC-10720-67952720329). Announcements, assignments, readings, etc., will be posted there. You should be familiar with Canvas. If you need help with Canvas, visit the [Canvas Getting Started Guide for Students](https://community.canvaslms.com/docs/DOC-10701).

# Course Requirements {#sec-requirements}

Course grades will be based on the following:

-   Attendance, participation, and discussion (20%)
-   Response papers (20%)
-   Case study: Presentation (15%%)
-   Case study: Written analysis (15%)
-   Group Project: Campaign planning proposal (30%)

## Attendance, Participation, and Discussion (20%)

Much of the learning that occurs in this course will be in a seminar-style, discussion setting. To make this work—and make this fun—you will need to be prepared to vigorously debate and discuss the material. It is not enough that you just come to class. You are expected to actively discuss the readings and critically analyze their contents. More information on the University attendance policy can be found [here](https://catalog.utah.edu/pages/8Fjihzb4XouQv5OY0ZiE).

Our goal is **knowledge integration**--connecting seemingly disparate ideas and fitting them together in a larger picture--to provide a broad context for advancing our understanding. The best way to integrate knowledge from this class with what you already know is to:

-   Make sure you **read deeply**, actively drawing out the implications of the readings and connecting them to other concepts and ideas that you have learned.
-   **Participate actively** in the class, challenging the evidence provided by the studies, by me, or by other students. 
-   **Ask questions** if there is something you do not understand. Other students are likely to have the same question.

::: callout-note
Respectful disagreement and healthy debate is good and encouraged in all my courses.
:::

## Response Papers (20%)

You will write 3 response papers during the semester. Response papers should be **at least 500 words**. A good response paper will summarize and critique the readings for the day. Your response should identify common threads between the readings and what you already know, and critically engage with the ideas and concepts in the assigned readings.

Your response papers are due at the end of the day via Canvas for the class for which you choose to write a response. You should submit your response paper as a **PDF** on Canvas.

## Case Study: Presentations (15%)

Over the course, each student will present one campaign. Presentations will be scheduled during the first day of the course.

Presentations should include **(1) a summary of the case**, **(2) an analysis and a critique of the case**, and **(3) your conclusions**. In the summary, you should provide enough information about the case, including what the case was about, what the organization did, the results of the campaign, etc. In the analysis and critique, you must analyze the effectiveness of the campaign. To assess effectiveness,you can compare your case to other case(s) and/or apply any theories they have learned in this or other classes. In the conclusion, you must determine whether the case serves as a good benchmark of an excellent campaign.

Presentations are expected to take about **30 minutes** followed by a Q&A session. 

While scheduling presentations later in the semester will allow students more time to prepare, the expectation is that these presentations will be of higher quality.

Please note that students who do not present their case study on the assigned day will receive a 50% deduction to their presentation grade as a penalty. If any emergency occurs, please contact the instructor ASAP.

After the presentation, you must submit the presentation slides as a **PDF** file on Canvas. 

## Case Study: Written Analyses (15%)

Over the course, you will see other students’ campaign case study presentations. Each student will write and analysis of 10 campaigns. The paper should include **(1) a short summary of the case** and **(2) your own evaluation of the case (not the presenter’s evaluation)**, including what was good and what was not, and what they would do if they were in charge of that campaign. 

Each analysis should be **at least 250 words**. Due dates will be posted on Canvas and are included in the schedule below. Submit written analyses as **PDF** files on Canvas.

## Group Project: Campaign Planning Proposal (30%)

Your project will be a campaign planning proposal where your team will develop a health campaign plan related to a topic of your choice. The proposal is designed to provide an opportunity for students to apply the materials covered in readings and in class. Students are assigned to groups and will collaborate to select a specific health or risky behavior. More detailed information will be provided in class.

There will be assignments throughout the semester designed to help you complete your proposal.

1) **Topic and preliminary research presentation.** Teams will decide on a specific health or risky behavior to work on and will conduct preliminary research. Then, your team will present this research in class and receive feedback from other students and the instructor.

2) **Focus group interviews (FGI) protocol, transcription, and summary.** Based on your preliminary research, your team will identify your research needs and conduct focus group interviews (FGI) with other students in the class. Before conducting interviews, you will work on the FGI protocol for submission. After the interviews, your team will transcribe and summarize what you learned from the FGI.

3) **Final presentation.** Your team will present your health/risk communication campaign proposal in class.

3) **Written proposal.** Your team will prepare and submit a written proposal via Canvas at the end of the semester.

# Course Grading

Grades in this course will be based on the following scale.

| Grade | Score (%)   |
|-------|:-----------:|
| A     | 93 to 100   |
| A-    | 90 to \< 93 |
| B+    | 87 to \< 90 |
| B     | 83 to \< 87 |
| B-    | 80 to \< 83 |
| C+    | 77 to \< 80 |
| C     | 73 to \< 77 |
| C-    | 70 to \< 73 |
| D+    | 67 to \< 70 |
| D     | 63 to \< 67 |
| D-    | 60 to \< 63 |
| E     | \< 60       |

You can and should check your grade regularly on Canvas. Information on the grade points assigned to letter grades and how to calculate your GPA can be found [here](https://advising.utah.edu/academic-standards/gpa-calculator-new.php).

::: callout-important
If you wish to dispute your grade on any assignment, you must put your concerns in writing (please adhere to the [course email policy](#sec-policies)) via email to [Prof. Yeo](sara.yeo@utah.edu), clearly outlining your rationale. These concerns must be presented within one week of receiving your grade.
:::

# Course Policies {#sec-policies}

By enrolling in this course, you agree to:

1.  respect the instructor and all members of the course;
2.  engage with the content meaningfully;
3.  meet the requirements of this course; and
4.  abide by the course policies outlined in the syllabus.

This list represents the **minimal standards** to make the course a productive learning space. **Your final grade may be reduced by 1% each time you engage in disruptive and/or disrespectful behaviors**.

## Email Policy

::: callout-note
It is critical that you check your University email account frequently and that you use your University email account to contact your instructors.
:::

**I will not respond to emails originating from a non-University account (e.g., Google, Yahoo, etc.)**. Using a non-University account runs the risk of your message being diverted to Spam/Junks and your message may not reach me in a timely fashion, if at all. Emails should be written clearly and professionally with correct spelling and grammar. **Emails that do not conform to these rules will not receive a response**. When you contact your instructors, you are expected to be professional in your communication. This includes:

-   Providing a relevant description or statement in the email subject line. Do not leave the subject line blank or simply write, "Hi."
-   Providing your full name, uNID, and class section in the message.
-   Using appropriate salutations (e.g., Dr. or Prof. Yeo; recipient's name, if appropriate).
-   Using paragraphs, not just long blocks of text.
-   Proofreading your writing.
-   Providing a clear description of your problem and all relevant information.
-   Being polite in your emails. For example, you should end your messages with a signature, such as "sincerely," "regards," or "thank you."

## Course Civility

Communication allows us to engage with others and broaden our perspectives. How concepts are discussed, in the physical or virtual classroom, is part of that process. Diverse perspectives and experiences will inform and enhance our discussions. Each member of the class is expected to foster a respectful, generous, and supportive environment that makes room for productive difference and reasoned debate. Spirited discussion is encouraged. However, incivility is a different story entirely. Here is the basic etiquette that will be expected in the course:

-   Please address your classmates by name. There is a human being on the other side of the screen/room who also has struggles, doubts, and bad days.
-   **Civil** disagreement is encouraged! Approach differences in a manner that seeks clarity and better understanding by asking productive questions and by providing counterarguments that are supported with evidence.
-   Anytime you have a strong emotional reaction to something, pause before responding. Always seek to provide an argument that is supported by credible evidence based on the concepts discussed in this course.

## Academic Misconduct

::: callout-warning
Academic misconduct will be punished to the fullest extent possible. Anyone found guilty of academic misconduct should expect to fail this course.
:::

It is expected that students comply with University of Utah policies regarding academic honesty, including but not limited to refraining from cheating, plagiarizing, misrepresenting one's work, and/or inappropriately collaborating. This includes the use of generative artificial intelligence (AI) tools without citation, documentation, or authorization. Students are expected to adhere to the prescribed professional and ethical standards of the profession/discipline for which they are preparing. Any student who engages in academic dishonesty or who violates the professional and ethical standards for their profession/discipline may be subject to academic sanctions as per the University of Utah's Student Code: Policy 6-410: Student Academic Performance, Academic Conduct, and Professional and Ethical Conduct.

Plagiarism and cheating are serious offenses and may be punished by failure on an individual assignment, and/or failure in the course. Academic misconduct, according to the University of Utah Student Code:

> "... includes, but is not limited to, cheating, misrepresenting one's work, inappropriately collaborating, plagiarism, and fabrication or falsification of information...It also includes facilitating academic misconduct by intentionally helping or attempting to help another to commit an act of academic misconduct."

For details on plagiarism and other important course conduct issues, see the U's [Code of Student Rights and Responsibilities](http://regulations.utah.edu/academics/6-400.php).

## Curriculum Accommodations

Curriculum accommodations take two forms--scheduling and content accommodations. On a case-by-case basis, if you submit the appropriate documentation in advance of the conflict (when possible), scheduling accommodations for assignments may be considered.

If you anticipate a scheduling conflict, please speak with me as soon as possible. Without exception, it is your responsibility to plan for any scheduling conflict.

**There will be no content accommodations in this course**. The material has been selected for its pedagogical value in relation to the concepts we are engaging. It is your responsibility to review the course materials to be sure that this is a course you wish to take. More information on the University's accommodation policy can be found in [Policy 6-100](https://regulations.utah.edu/academics/6-100.php).

## Emergency Plan

In the event of a University-wide emergency which prevents face-to-face meetings, students should continue to stay current with our schedule as posted in this syllabus and to attend to the course website on Canvas. Information about the status of assignments and other course work due during this period will be addressed on Canvas and, if necessary, by way of email.

# University Policies {#sec-Upolicies}

## ADA

The University of Utah seeks to provide equal access to its programs, services, and activities for people with disabilities. All written information in this course can be made available in an alternative format with prior notification to the Center for Disability & Access (CDA). CDA will work with you and the instructor to make arrangements for accommodations. Prior notice is appreciated. To read the full accommodations policy for the University of Utah, please see Section Q of the Instruction & Evaluation regulations. In compliance with ADA requirements, some students may need to record course content. Any recordings of course content are for personal use only, should not be shared, and should never be made publicly available. In addition, recordings **must** be destroyed at the conclusion of the course. If you will need accommodations in this class, or for more information about what support they provide, contact the [Center for Disability & Access](https://disability.utah.edu/).

## Safety

**Safety at the U.** The University of Utah values the safety of all campus community members. You will receive important emergency alerts and safety messages regarding campus safety via text message. For more safety information and to view available training resources, including helpful videos, visit safeu.utah.edu.

**Addressing Sexual Misconduct.** Title IX makes it clear that violence and harassment based on sex and gender (includes sexual orientation and gender identity/expression) is a civil rights offense subject to the same kinds of accountability and the same kinds of support applied to offenses against other protected categories such as race, national origin, color, religion, age, status as a person with a disability, veteran's status or genetic information. If you or someone you know has been harassed or assaulted, you are encouraged to report it to the [Title IX Coordinator in the Office of Equal Opportunity and Affirmative Action](https://oeo.utah.edu/) or the [Office of the Dean of Students](https://deanofstudents.utah.edu/). To report to the police, contact [Campus Police](https://dps.utah.edu/). If you do not feel comfortable reporting to authorities, the U's Victim-Survivor Advocates provide free, confidential, and trauma-informed support services to students, faculty, and staff who have experienced interpersonal violence. To privately explore options and resources available to you with an advocate, contact the [Center for Student Wellness](http://wellness.utah.edu/).

\newpage 

# Course Schedule

The schedule is tentative. Any changes will be announced on Canvas. Your continued enrollment in this course constitutes an agreement to abide by the policies and procedures in this syllabus.

## Friday (20-Jun; Day 1): Paradigms/Some Early Communication Models

Readings:

-   Course syllabus
-   Schwartz, M. A. (2008). The importance of stupidity in scientific research. *Journal of Cell Science*, *121*(11), 1771–1771. https://doi.org/10.1242/jcs.033340

Sign up for Case Study Presentations.

---

## Monday (23-Jun; Day 2): The Nature of Theory

Readings:

-   Hornik, R., & Yanovitzky, I. (2003). Using theory to design evaluations of communication campaigns: The case of the National Youth Anti-Drug Media Campaign. *Communication Theory*, *13*(2), 204–224. https://doi.org/10.1111/j.1468-2885.2003.tb00289.x

Case Study Presentation:

-   Student 1

Case Study: Written Analysis #1 due on Canvas.

---

## Tuesday (24-Jun; Day 3): Perceptions of Risk

Readings:

-   Slovic, P., Fischhoff, B., & Lichtenstein, S. (1982). Why study risk perception? *Risk Analysis*, *2*(2), 83–93. https://doi.org/10.1111/j.1539-6924.1982.tb01369.x

Case Study Presentation:

-   Student 2

Case Study Written Analysis #2 due on Canvas.

---

## Wednesday (25-Jun; Day 4): Knowledge and Risk Perceptions

Readings:

-   Simis, M. J., Madden, H., Cacciatore, M. A., & Yeo, S. K. (2016). The lure of rationality: Why does the deficit model persist in science communication? *Public Understanding of Science*, *25*(4), 400–414. https://doi.org/10.1177/0963662516629749

Case Study Written Analysis #3 due on Canvas.

Group Project: Topic and Preliminary Research Presentation

---

## Thursday (26-Jun; Day 5): Media Coverage of Risks

Readings:

-   Mayeda, A. M., Boyd, A. D., Paveglio, T. B., & Flint, C. G. (2018). Media representations of water issues as health risks. *Environmental Communication*, *13*(7), 926–942. https://doi.org/10.1080/17524032.2018.1513054

Group Project: Topic and Preliminary Research Presentation

---

## Friday (27-Jun; Day 6): Framing

Readings:

-   Tversky, A., & Kahneman, D. (1981). The framing of decisions and the psychology of choice. *Science*, *211*(4481), 453. https://doi.org/10.1126/science.7455683

Case Study Presentation:

-   Student 3

Case Study Written Analysis #4 due on Canvas.

---

## Monday (30-Jun; Day 7): Framing, Agenda Setting, and Priming

Readings:

-   Scheufele, D. A., & Tewksbury, D. (2007). Framing, agenda setting, and priming: The evolution of three media effects models. *Journal of Communication*, *57*(1), 9–20. https://doi.org/10.1111/J.1460-2466.2006.00326.X

Case Study Presentation:

-   Student 4

Case Study Written Analysis #5 due on Canvas.

--- 

## Tuesday (1-Jul; Day 8): Models of Information Processing (ELM, HSM)

Readings:

-   Luttrell, A. (2018). *Dual Process Models of Persuasion*. In Oxford Research Encyclopedia of Psychology. https://doi.org/10.1093/acrefore/9780190236557.013.319

Case Study Written Analysis #6 due on Canvas.

Group Project: Work on FGI, transcription, and summary

--- 

## Wednesday (2-Jul; Day 9): Tailoring and Targeting

Readings:

-   Rimer, B. K., & Kreuter, M. W. (2006). Advancing tailored health communication: A persuasion and message effects perspective. *Journal of Communication*, *56*(suppl_1), S184–S201. https://doi.org/10.1111/j.1460-2466.2006.00289.x

Group Project: Work on FGI, transcription, and summary

---

## Thursday (3-Jul; Day 10): Health Belief Model

Readings:

-   Janz, N. K., & Becker, M. H. (1984). The Health Belief Model: A decade later. *Health Education Quarterly*, *11*(1), 1–47. https://doi.org/10.1177/109019818401100101

Case Study Presentation:

-   sign up here

Case Study Written Analysis #7 due on Canvas.

---

## Friday (4-Jul; Day 11): Social Amplification of Risk

Readings:

-   Kasperson, R. E., Webler, T., Ram, B., & Sutton, J. (2022). The social amplification of risk framework: New perspectives. *Risk Analysis*, *42*(7), 1367–1380. https://doi.org/10.1111/risa.13926

Case Study Presentation:

- sign up here

Case Study Written Analysis #8 due on Canvas.

---

## Monday (7-Jul; Day 12): Health Communication Campaigns & Social Media

Readings:

-   McGurk, M. D., Ogawa, G., Inoue, K., Wills, C., Ching, L. K., Shalaby, A. K., Kong, N., Hansen Smith, H., Lee, J., Irvin, L., & Keliikoa, L. B. (2025). Sweet Lies! Lessons learned from Hawai‘i’s sweetened fruit drink countermarketing campaign. *Journal of Health Communication*, *30*(sup1), 14–27. https://doi.org/10.1080/10810730.2025.2461588

Case Study Presentation:

- sign up here

Case Study Written Analysis #9 due on Canvas.

---

## Tuesday (8-Jul; Day 13): Making Health Communication Programs Work

Readings:

-   National Cancer Institute. (2001). *Making Health Communication Programs Work*. U.S. Department of Health & Human Services. https://stacks.cdc.gov/view/cdc/24017

Case Study Presentation:

-   sign up here

Case Study Written Analysis #10 due on Canvas.

---

## Wednesday (9-Jul; Day 14): Group Project Presentations

Group Project: Final Presentations

---

## Thursday (10-Jul; Day 15): Group Project Presentations

Group Project: Final Presentations.