---
title: "GP.G: Statistical Tests (15 points)"
pagetitle: "COMM 3710: GP.G"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
urlcolor: blue
---

# Resources
- [COMM 3710: Getting Started with R](https://sarakyeo.github.io/COMM-3710-bookdown/docs/index.html)
- [Week 9 lecture content](https://sarakyeo.github.io/COMM-3710/week9.html)

---

# Instructions

## Step 1
List your hypotheses and/or research questions (RQs) in your PDF submission.


## Step 2 {.tabset .tabset-fade .tabset-pills}
### Question
For each hypothesis and/or RQ, determine what the appropriate statistical test is for your main two variables of interest. Your options are:

- Independent samples *t*-test
- Analysis of variance (ANOVA)
- Chi-squared test of independence
- Pearson's correlation

List the hypothesis test chosen and provide a rationale for your decision (see Example tab).

### Example
**H1: The average number of hours spent on social media per week will be positively associated with higher anxiety scores.**

To test H1, I will use Pearson's correlation. The independent variable, average number of hours spent on social media per week, is continuous and the dependent variable, respondents' anxiety scores, is also continuous. Therefore, Pearson's correlation is an appropriate test of this relationship.


## Step 3
Load your data, the necessary R packages, and run the appropriate statistical test for each hypothesis and/or research question in R.

> Your R script must be logical and easy-to-follow, contain **clear** and **meaningful** annotations, and run its in entirety.

Comments should answer the question of "why" (instead of "what") you are using/running a specific command.

Include clear commands to:

1) set your working directory;
2) load/read the data into the object/data frame with which you are working in the rest of your script; and
3) install and load all necessary packages at the beginning of the script. As you work, you may find that you need libraries that you have not loaded. Simply go back to the beginning of your script and include commands to load the libraries there.


## Step 4 {.tabset .tabset-fade .tabset-pills}
### Question 
Interpret your findings and write a paragraph about each.

### Sample Write-Ups {.tabset .tabset-fade}

#### Independent samples *t*-tests
An independent samples *t*-test was performed comparing the mean consistency scores of college students and individuals diagnosed with schizophrenia. As predicted, the schizophrenics (M = .76, SD = .20, N = 100) were more illogical than the college students (M = .17, SD = .13, N = 97), *t*(17) = 7.53, *p* < .001, two-tailed.

#### Analysis of variance (ANOVA)
When examining the association between current number of cigarettes smoked (quantitative response) and past year nicotine dependence (categorical explanatory), an analysis of variance (ANOVA) revealed that among daily, young adult smokers (my sample), those with nicotine dependence reported smoking significantly more cigarettes per day (M = 14.6, SD = 9.15) compared to those without nicotine dependence (M = 11.4, SD = 7.43), *F*(1, 1313) = 44.68, *p* =.0001.

#### Chi-squared test of independence
When examining the association between lifetime major depression (categorical response) and past year nicotine dependence (categorical explanatory), a chi-square test of independence revealed that among daily, young adults smokers (my sample), those with past year nicotine dependence were more likely to have experienced major depression in their lifetime (36.2%) compared to those without past year nicotine dependence (12.7%), *$\chi$^2^* = 88.60, *p* = 0001.

#### Correlation
Among daily, young adult smokers (my sample), the correlation between number of cigarettes smoked per day (quantitative) and number of nicotine dependence symptoms experienced in the past year (quantitative) was 0.17 (*p* = .0001), suggesting that only 3% (i.e., 0.17^2) of the variance in number of current nicotine dependence symptoms can be explained by number of cigarettes smoked per day.


## Submission
Submit the following on Canvas:

- A **.R file** with all commands and comments. The commands in this R script must run in its entirety and in order (i.e., from top to bottom) and include commands to set the working directory, load packages, and read data into R.
- A **PDF file** of the graphs and other required elements.
   - Write up your findings from all your hypothesis tests and submit your assignment as a **PDF** on Canvas.
   - Clean up your R code and submit the **.R file**. This file should be neat and include comments.

